{
   const double tmp0 = ADM_3METRIC[GXX]*ADM_3METRIC[SHIFTX] + ADM_3METRIC[GXY]*ADM_3METRIC[SHIFTY] + ADM_3METRIC[GXZ]*ADM_3METRIC[SHIFTZ];
   const double tmp1 = ADM_3METRIC[GXY]*ADM_3METRIC[SHIFTX] + ADM_3METRIC[GYY]*ADM_3METRIC[SHIFTY] + ADM_3METRIC[GYZ]*ADM_3METRIC[SHIFTZ];
   const double tmp2 = ADM_3METRIC[GXZ]*ADM_3METRIC[SHIFTX] + ADM_3METRIC[GYZ]*ADM_3METRIC[SHIFTY] + ADM_3METRIC[GZZ]*ADM_3METRIC[SHIFTZ];
   g4dn[0][0] = -(ADM_3METRIC[LAPSE])*(ADM_3METRIC[LAPSE]) + ADM_3METRIC[SHIFTX]*tmp0 + ADM_3METRIC[SHIFTY]*tmp1 + ADM_3METRIC[SHIFTZ]*tmp2;
   g4dn[0][1] = tmp0;
   g4dn[0][2] = tmp1;
   g4dn[0][3] = tmp2;
   g4dn[1][0] = tmp0;
   g4dn[1][1] = ADM_3METRIC[GXX];
   g4dn[1][2] = ADM_3METRIC[GXY];
   g4dn[1][3] = ADM_3METRIC[GXZ];
   g4dn[2][0] = tmp1;
   g4dn[2][1] = ADM_3METRIC[GXY];
   g4dn[2][2] = ADM_3METRIC[GYY];
   g4dn[2][3] = ADM_3METRIC[GYZ];
   g4dn[3][0] = tmp2;
   g4dn[3][1] = ADM_3METRIC[GXZ];
   g4dn[3][2] = ADM_3METRIC[GYZ];
   g4dn[3][3] = ADM_3METRIC[GZZ];
}
